### ISSUE TITLE
Remove name mappings for windows

### ISSUE THREAD

**Issue by vweevers** [benderjs/browser-launcher2#26]
The [winDetectMap](https://github.com/benderjs/browser-launcher2/blob/master/lib/detect.js#L49) should be updated, or removed all together. The "ff" to "firefox" mapping is old, as is "phantom" to "phantomjs". Chromium is not supported by `win-detect-browsers` (and chromium has no Windows installer as far as I know, so it's not detectable) so it can be left out. The only one that needs mapping is "chrome" to "google-chrome". 

```js
winDetectMap = {
  chrome: 'google-chrome',
  chromium: 'chromium-browser',
  ff: 'firefox',
  phantom: 'phantomjs',
  safari: 'safari',
  ie: 'ie',
  opera: 'opera'
};
```

**Comment by gregpabian** [comment]
Resolved with bdb2ba05993685b6742944f2fb4b5461b3f33047 and 217f2122f97b8294d970b9abc753ed4273db160b
